baseURL = "https://son-dongwoo.github.io/"
languageCode = "en-us"
title = "Son-Dongwoo's Blog"
theme = "PaperMod"

[params]
  author = "Son-Dongwoo"
  description = "Welcome to my blog!"
  showDate = true
  showReadingTime = true
  assets.disableFingerprinting=true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2